### ISSUE TITLE
error in loading pharo 8 

### ISSUE THREAD

**Issue by sanjayminni** [ba-st/Willow-Bootstrap#94]
There is an error when trying to load Willow-bootstrap and willow-JQueryUI using
the Metacello script

(prior to this Willow 12.1.0 was loaded first in Pharo 8 / Windows 10)

Possibly this has something to do with the following line in setUpDependencies:
baseline: 'Willow' with: [ spec repository: 'github://ba-st/Willow:v12/source' ]

This is worked around by pulling in BaselineOfWillow-Bootstrap / JqueryUI thru iceberg, then editing Willow:v12 to Willow:12.1.0. it then successfully loads thru iceberg
right-click metacello(default)

as responded Probably v12 must be equivalent to the latest v12.x release.

**Comment by gcotelli** [comment]
@sanjayminni are you doing something like this??

```smalltalk
Metacello new
	baseline: 'Willow';
	repository: 'github://ba-st/Willow:v12.1.0/source';
	load.
	
Metacello new
	baseline: 'WillowBootstrap';
	repository: 'github://ba-st/Willow-Bootstrap:v11.3.2/source';
	load.
```

If that is the case you must be getting a debugger with some kind of Metacello conflict message. This happens because Metacello is not smart enough to figure out that v12.1.0 is the same commit than v12. 

Your options here are:
1. Load Willow using v12 instead of an specific version (or just let Willow-Bootstrap and Willow-JQueryUI load it for you, you don't need to load the dependencies by hand). All the latest major versions are prepared to work without conflicts, so if you load Willow:v12 and Willow-Bootstrap:v11 everything will just work.

2. If you still want to load an specific version and use it in the dependent projects you need to `lock` the Metacello config. For example:
```smalltalk
Metacello new
	baseline: 'Willow';
	repository: 'github://ba-st/Willow:v12.1.0/source';
	lock;
	load.
	
Metacello new
	baseline: 'WillowBootstrap';
	repository: 'github://ba-st/Willow-Bootstrap:v11.3.2/source';
	onLock: [ :lock | lock honor ];
	load.
```

BTW, this is a general problem with Metacello not Willow specific.

**Comment by sanjayminni** [comment]
Yes I am getting the debugger with Metacello conflict message
![WillowMetacelloLoadError](https://user-images.githubusercontent.com/12030766/70731525-d787f700-1d2c-11ea-895e-184f41a101ae.jpg)

I had loaded Willow separately first followed by trying to load Willow-Bootstrap

Metacello new
	baseline: 'Willow';
	repository: 'github://ba-st/Willow:release-candidate/source';
	load.
	
Metacello new
	baseline: 'WillowBootstrap';
	repository: 'github://ba-st/Willow-Bootstrap:release-candidate/source';
	load.

I will work thru alternatives suggested by you, but in the meanwhile have loaded it by editing BaselineOfWillowBootstrap

I wish I had known of this Metacello quirk earlier as I have faced this on several occasions with different packages
